"$schema"="https://gitlab.com/Lanastara/lanastara_foss/-/raw/v0.3.0/schema.json?ref_type=tags"
# Text that will be printed between each Module.
module_separator = " "
# Controls whether colors are reset at the end of output.
# Try this if your prompt displays a blank space at the end.
# reset_color = true
# Timeout after wich the process is teminated.
# timeout = 1000

# Controls the behaviour of the bookmark finding algorythm.
[bookmarks]
# Controls how far we are looking back to find bookmarks.
exclude = []
# Controls how far we are looking back to find bookmarks.
# search_depth = 0

[[module]]
# Prints information about bookmarks in the working copies ancestors.
type = "Bookmarks"
# Text that will be rendered between each bookmark.
separator = " "
# Color the text will be rendered in. Supports PascalCase, snake_case, true color, and hex.
# Examples: "Magenta", "bright_blue", "#ff00ff", or color.TrueColor = { r = 255, g = 0, b = 255 }
color = "Magenta"
# Text background color. Can also be TrueColor.
# bg_color = "Yellow"
# Text attributes can be enabled on any styled section.
# bold = true
# italic = true
# underline = true
# A suffix that will be printed when the given bookmark is behing the working copy.
behind_symbol = "⇡"
# Ignore commits without descriptions when counting bookmark distance: "None", "Current", or "All".
# ignore_empty_commits = "None"
# Maximum amout of bookmarks that will be rendered.
# max_bookmarks = 1
# Maximum length the bookmark name will be truncated to.
# max_length = 10
# Surround the bookmark names with double-quotes
# surround_with_quotes = true

[[module]]
# Prints the working copies commit text
type = "Commit"
# Maximum length the commit text will be truncated to.
max_length = 24
# color = "Green"
# bg_color = "Yellow"
# default text if the commit description is not set
# empty_text = "n/a"
# Surround the commit text with double-quotes
# surround_with_quotes = true
# Show the previous commit's description when the current commit is empty.
# show_previous_if_empty = false
# previous_message_symbol = "⇣"
# Enable rendering ids by adding these style tables.
# [module.change]
# color = "Magenta"
# [module.commit]
# color = "Blue"

[[module]]
# Prints a warning if the working copy contains any conflicts, is divergent or hidden
type = "State"
# Text that will be printed between each Warning.
separator = " "

[module.conflict]
text = "(CONFLICT)"
color = "Red"
# bg_color = "Yellow"

[module.divergent]
text = "(DIVERGENT)"
color = "Cyan"
# bg_color = "Yellow"

[module.hidden]
text = "(HIDDEN)"
color = "Yellow"
# bg_color = "Yellow"

[module.immutable]
disabled = false
text = "(IMMUTABLE)"
color = "Yellow"

[module.empty]
disabled = false
text = "(EMPTY)"
color = "Yellow"

[[module]]
# Prints the amount of changes in the working copy
type = "Metrics"
color = "Magenta"
# bg_color = "Yellow"
# Hide the metrics module when there are no changes [0 +0-0].
# hide_if_empty = true
# Controls how the changes are rendered, use {added}, {removed} and {changed} to render the number of changes.
template = "[{changed} {added}{removed}]"

[module.changed_files]
# Controlls how the number of changed files is rendered.
# suffix = ""
# prefix = ""
color = "Cyan"
# bg_color = "Yellow"

[module.added_lines]
# Controlls how the number of changed files is rendered.
prefix = "+"
# suffix = ""
color = "Green"
# bg_color = "Yellow"

[module.removed_lines]
# Controlls how the number of removed lines is rendered.
prefix = "-"
# suffix = ""
color = "Red"
# bg_color = "Yellow"
